install:
	cp ethers_schreiben_fuer_wakeonlan /usr/bin/
	cp ethers_schreiben /etc/cron.d/ 
	/usr/bin/ethers_schreiben_fuer_wakeonlan

uninstall: 
	rm -rf /usr/bin/ethers_schreiben_fuer_wakeonlan /etc/ethers /etc/cron.d/ethers_schreiben

