install:
	cp ethers-schreiben-fuer-wakeonlan /usr/bin/
	cp ethers-schreiben /etc/cron.d/ 
	/usr/bin/ethers-schreiben-fuer-wakeonlan

uninstall: 
	rm -rf /usr/bin/ethers-schreiben-fuer-wakeonlan /etc/ethers /etc/cron.d/ethers-schreiben

