#!/bin/bash
for lehrer in $(ls /home/teachers) ; 
do 
  for klasse in $(sophomorix-teacher -i --teacher $lehrer |
      grep -v "AdminClasses"|
      grep -v "Add a class") ; 
  do 
      sophomorix-teacher --teacher $lehrer --remove $klasse ; 
  done ; 
done