install:
	sudo cp lehrer_aus_klassen_austragen /usr/bin/lehrer_aus_klassen_austragen;
	sudo cp lehrer_aus_klassen_austragen_cron /etc/cron.d/lehrer_aus_klassen_austragen

uninstall: 
	sudo rm /usr/bin/lehrer_aus_klassen_austragen /etc/cron.d/lehrer_aus_klassen_austragen

