#!/bin/bash
# firefox-einstellungen-loeschen  <jesko.anschuetz@linuxmuster.net> März 2013
# Dieses Skript löscht in allen Schüler- und Lehrerhomeverzeichnissen die Firefox-Einstellungen.
# Einerseits im Ordner Home_auf_Server/Einstellungen und andererseits direkt im Server-Home.
# Damit werden sowohl Ubuntu 10.04 als auch Ubuntu 12.04 Clients ordnungsgemäß zurückgesetzt.

function lehrereinstellungen_loeschen() {
  # Lehrer bearbeiten
  for LEHRER in $(ls /home/teachers/)
  do
    echo Entferne Firefoxeinstellungen von $LEHRER;
    rm -r /home/teachers/$LEHRER/Einstellungen/firefox 2>/dev/null;
    rm -r /home/teachers/$LEHRER/.mozilla 2>/dev/null;
  done
}

function schuelereinstellungen_loeschen() {
  # Schüler bearbeiten
  for KLASSE in $(ls /home/students/)
  do
    for SCHUELER in $(ls /home/students/$KLASSE)
    do
       echo Entferne Firefoxeinstellungen von $KLASSE - $SCHUELER
       rm -r /home/students/$KLASSE/$SCHUELER/Einstellungen/firefox 2>/dev/null
       rm -r /home/students/$KLASSE/$SCHUELER/.mozilla 2>/dev/null
    done
  done
}

PS3="Durch Tippen der Ziffer wählen:"
echo "Wessen Firefox-Einstellungen sollen gelöscht werden?"
select auswahl in Lehrer Schüler ALLE Ende
do
   case "$auswahl" in
        "")  echo "Ungültige Auswahl" ;;
    Lehrer)  lehrereinstellungen_loeschen ;  break ;;
   Schüler)  schuelereinstellungen_loeschen ; break ;;
      ALLE)  lehrereinstellungen_loeschen ; schuelereinstellungen_loeschen ; break ;;
         *)  echo "Ende"; break ;;
   esac
done







