install:
	[[ -d /etc/schultag ]] || mkdir /etc/schultag
	cp *.conf /etc/schultag
	cp ist-heute-schultag /usr/bin/
	cp ist-schultag /usr/bin/

uninstall: 
	rm -rf /usr/bin/ist-heute-schultag /usr/bin/ist-schultag /etc/schultag

