#!/bin/bash
verzeichnis = $(pwd)
echo "erstelle Verzeichnis /var/www/weblog"
mkdir /var/www/weblog  && echo "...erledigt"
echo "kopiere Dateien in dieses Verzeichnis"
cp ./* /var/www/weblog  && echo "...erledigt"
echo "wechsle in das Verzeichnis"
cd /var/www/weblog  && echo "...erledigt"
echo "erstelle Verzeichnisschutz"
. htaccess_erzeugen && echo "...erledigt"
echo "passe Berechtigungen der Dateien an"
chmod 666 wla_weblogauswertung.conf && echo "wla_weblogauswertung.conf ...erledigt."
chmod 666 filterausdruck && echo "filterausdruck ...erledigt."
chmod 666 suchbegriffe && echo "suchbegriffe ...erledigt."
echo "access.log vom IPFIRE kopieren"
/usr/bin/scp -P 222 root@ipfire:/var/log/squid/access.log /var/www/weblog/ && echo "...erledigt"
echo "Temporaere Dateien loeschen"
cd $verzeichnis
echo "Jetzt muss nur noch ein Cron-Job erstellt werden!"


